IEM-Product/IEMProduct/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using IEMProduct.Service;
using DataAccessHandler.Models.IEMProduct;
namespace IEMProduct.Controllers
{
    public class LoginController : Controller
    {
        log4net.ILog logger = log4net.LogManager.GetLogger(typeof(LoginController));
        Proxy_Model ObjProxy = new Proxy_Model();
        Login_Service serviceObj = new Login_Service();
        DataTable dt = new DataTable();
        // GET: Login
        public ActionResult Login()
        {
            Session.Remove("Employee_Gid");
            Session.Remove("Employee_Code");
            Session.Remove("Employee_Name");
            Session.Remove("Grade_Gid");
            Session.Remove("Employee_Role");
            Session.Remove("Proxy_InsertBy");
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string pass, string ddlLoginMode, string proxyFromId = "0")
        {
            try
            {
                dt = serviceObj.CheckUserCredential(username, pass, ddlLoginMode, proxyFromId);
                if (dt.Rows.Count > 0)
                {
                    if (dt.Rows[0][0].ToString() != "SQLEXCEPTION" && dt.Rows[0][0].ToString() != "Invalid Credential")
                    {
                        Session["Employee_Gid"] = Convert.ToInt64(dt.Rows[0]["employee_gid"].ToString());
                        Session["Employee_Code"] = dt.Rows[0]["employee_code"].ToString();
                        Session["Employee_Name"] = dt.Rows[0]["employee_name"].ToString();
                        Session["Grade_Gid"] = Convert.ToInt64(dt.Rows[0]["employee_grade_gid"].ToString());
                        Session["Proxy_InsertBy"] = Convert.ToInt64(dt.Rows[0]["InsertBy"].ToString());
                        Session["Employee_Role"] = dt.Rows[0]["employee_role"].ToString();
                        //if(Session["Employee_Role"].ToString().Equals("P"))
                        //{
                        //      return RedirectToAction("Claim", "Claim", new {area ="EOW"});
                        //}
                        //else
                        //{
                        //return RedirectToAction("Workbench", "Workbench");
                        //}            
                        return RedirectToAction("Workbench", "Workbench");
                    }
                    else
                    {
                        ViewBag.Message = "Please check.! Invalid User Credential.!";
                    }
                }
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
            }
            return View();
        }
        //Ramya Proxy
        public JsonResult Get_ProxyFrom(string ProxyFrom)
        {
            List<Proxy_Model> lst = new List<Proxy_Model>();
            try
            {
                lst = serviceObj.Get_ProxyFrom(ProxyFrom);
            }
            catch (Exception ex)
            {
                logger.Error(ex.ToString());
            }
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
    }
}

IEM-Product/IEMProduct/Controllers/ProfileController.cs
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IEMProduct.Service;
using Kendo.Mvc.Extensions;
using DataAccessHandler.Models.IEMProduct;
using System.Data;
using Newtonsoft.Json;
using DBHelper;
namespace IEMProduct.Controllers
{
    public class ProfileController : Controller
    {
        #region

        Profile_Service serviceObj = new Profile_Service();
        DataTable dt = new DataTable();
        DataTable result = new DataTable();
        DataRow dr;
        DataSet ds = new DataSet();
        Profile_Model Obj_Model = new Profile_Model();
        log4net.ILog log = log4net.LogManager.GetLogger(typeof(ProfileController));
        #endregion
        // GET: Profile
        public ActionResult Profile()
        {
            return View();
        }
        public ActionResult EmployeeProfile()
        {
            return View();
        }
        //Delegation Read

        public ActionResult ReadGrid([DataSourceRequest] DataSourceRequest request)
        {
            try
            {
                Int64 User_GID = Convert.ToInt64(Session["Employee_Gid"].ToString());
                Obj_Model.Action = "ALL";
                return Json(serviceObj.Get_EmployeeRead(Obj_Model).ToDataSourceResult(request));
            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();
            }

        }
        [HttpPost]
        public ActionResult GetEmpDetails(Profile_Model Obj_Model)
        {
            try
            {
                Obj_Model.Emp_Gid = Convert.ToInt64(Session["Employee_Gid"]);
                dt = serviceObj.GetEmpDetails_List(Obj_Model);
                return Json(JsonConvert.SerializeObject(dt), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();

            }
        }
        [HttpPost]
        public ActionResult GetEmpDetailsHirackey(Profile_Model Obj_Model)
        {
            try
            {
                List<tree_model> ModelList = new List<tree_model>();
                Obj_Model.Emp_Gid = Convert.ToInt64(Session["Employee_Gid"]);
                dt = serviceObj.GetEmpDetailsHirackey_List(Obj_Model);
                result = new DataTable();
                result.Clear();
                result.Columns.Add("s_no");
                result.Columns.Add("employee");
                result.Columns.Add("emplevel");
                result.Columns.Add("parent");

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    add_menu(Convert.ToInt32(dt.Rows[i]["s_no"]), dt.Rows[i]["employee"].ToString(), Convert.ToInt32(dt.Rows[i]["emplevel"]), Convert.ToInt32(dt.Rows[i]["parent"]));
                }

                foreach (DataRow datarow in result.Rows)
                {
                    if (datarow["parent"].ToString() == "0")
                    {
                        //tree_model nd = add_node(dt, datarow);
                        tree_model node = new tree_model();
                        tree_model _child_node;

                        node.id = datarow["s_no"].ToString();
                        node.text = datarow["employee"].ToString();
                        node.emplevel = datarow["emplevel"].ToString();
                        node.parent = datarow["parent"].ToString();


                        var rows = result.AsEnumerable()
                                       .Where(r => r.Field<string>("parent") == node.emplevel);

                        foreach (DataRow _row in rows)
                        {
                            _child_node = new tree_model();
                            _child_node = add_node(result, _row);
                            node.items.Add(_child_node);
                        }
                        ModelList.Add(node);
                    }
                }

                return Json(ModelList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();

            }
        }
        private class tree_model
        {
            public string id { get; set; }
            public string text { get; set; }
            public string emplevel { get; set; }
            public string parent { get; set; }
            public bool expanded = true;
            public List<tree_model> items = new List<tree_model>();
        }
        private tree_model add_node(DataTable _dt, DataRow _dr)
        {
            tree_model node = new tree_model();
            try
            {

                tree_model _child_node;

                node.id = _dr["s_no"].ToString();
                node.text = _dr["employee"].ToString();
                node.emplevel = _dr["emplevel"].ToString();
                node.parent = _dr["parent"].ToString();

                var rows = _dt.AsEnumerable()
                               .Where(r => r.Field<string>("parent") == node.emplevel);

                foreach (DataRow _row in rows)
                {
                    _child_node = new tree_model();
                    _child_node = add_node(_dt, _row);
                    node.items.Add(_child_node);
                }

            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());

            }
            return node;
        }

        private void add_menu(int id, string text, int emplevel, int parent)
        {
            try
            {
                dr = result.NewRow();
                dr["s_no"] = id.ToString();
                dr["employee"] = text;
                dr["emplevel"] = emplevel.ToString();
                dr["parent"] = parent.ToString();

                result.Rows.Add(dr);
            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
            }
        }

        //dropdown binding

        #region Common methods for dropdown bindings.
        //Designation
        public ActionResult Getdesignation(string parentcode)
        {
            List<Profile_Model> designationlist = new List<Profile_Model>();

            try
            {
                dt = serviceObj.Getdesignation(parentcode);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    Profile_Model designation = new Profile_Model();
                    designation.Designationid = Convert.ToInt64(dt.Rows[i][0].ToString());
                    designation.DesignationName = dt.Rows[i][1].ToString();
                    designationlist.Add(designation);
                }
                var jsonResult = Json(designationlist, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;

            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();
            }
            
        }

        //Grade
        public ActionResult GetGrade(string parentcode)
        {
            List<Profile_Model> gradelist = new List<Profile_Model>();

            try
            {
                dt = serviceObj.GetGrade(parentcode);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    Profile_Model grade = new Profile_Model();
                    grade.Gradeid = Convert.ToInt64(dt.Rows[i][0].ToString());
                    grade.GradeName = dt.Rows[i][1].ToString();
                    gradelist.Add(grade);
                }
                var jsonResult = Json(gradelist, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;
            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();
            }
           
        }



        //Department 
        public ActionResult GetDepartment(string parentcode)
        {
            List<Profile_Model> departmentlist = new List<Profile_Model>();

            try
            {
                dt = serviceObj.GetDepartment(parentcode);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    Profile_Model department = new Profile_Model();
                    department.Departmentid = Convert.ToInt64(dt.Rows[i][0].ToString());
                    department.Departmentname = dt.Rows[i][1].ToString();
                    departmentlist.Add(department);
                }
                var jsonResult = Json(departmentlist, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;

            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();
            }
           
        }
        //branch
        public ActionResult Getbranch(string parentcode)
        {
            List<Profile_Model> branchlist = new List<Profile_Model>();

            try
            {
                dt = serviceObj.Getbranch(parentcode);
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    Profile_Model branch = new Profile_Model();
                    branch.branchid = Convert.ToInt64(dt.Rows[i][0].ToString());
                    branch.branchname = dt.Rows[i][1].ToString();
                    branchlist.Add(branch);
                }

                var jsonResult = Json(branchlist, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;
                return jsonResult;

            }
            catch (Exception ex)
            {
                log.Error(ex.ToString());
                return View();
            }
           
        }
        //FC

IEM-Product/IEMProduct/Views/Shared/AuditTrail.cshtml
@using Kendo.Mvc.UI;
@using Kendo.Mvc.UI.Fluent;
@using Kendo.Mvc.Extensions;
@model  DBHelper.Attachment_Model

<html>
<head>
    <title></title>
    <style>
        div.k-window {
            display: inline-block;
            position: absolute;
            z-index: 10001;
            border-style: solid;
            border-width: 1px;
            padding-top: 1em;
            width: 50%;
            font-weight: normal;
        }

        .k-edit-form-container {
            position: relative;
            width: 100%;
            /*height:25%;*/
        }

        div#kwindow_attachment {
            overflow: hidden;
        }
    </style>
</head>
<body>     
    <div class="container-fluid">
        <div class="row" style="margin-top:10px;">
            <div class="col-sm-11">
                @using (Html.BeginForm("Attachment", "Attachment", FormMethod.Post, new { @id = "form3" }))
                {

                    @(Html.Kendo().Grid<DBHelper.Attachment_Model>().Name("Kgrid_AduitTrail")
                        .HtmlAttributes(new { style = "width:100%;line-height:2em;font-weight:normal;height: 200px !important;" })
                        .Columns(columns =>
                            {
                                columns.Bound(m => m.QiD).Width(20).Title("Queue ID").Hidden();
                                columns.Bound(m => m.EmpCode).Width(80).Title("Employee Code").Width(160);
                                columns.Bound(m => m.EmpName).Width(83).Title("Employee Name").Width(160);
                                columns.Bound(m => m.ActionDate).Width(120).Title("Action Date").Width(160);
                                columns.Bound(m => m.ActionType).Width(120).Title("Action Type").Width(160);
                                columns.Bound(m => m.Remarks).Width(120).Title("Remarks").Width(160);
                                columns.Bound(m => m.Designation).Width(120).Title("Designation").Width(160);

                            })
                            .Pageable(pageable => pageable
                            .Refresh(true)
                            .PageSizes(new List<object> { 15, 20, 500 })
                            .ButtonCount(5))
                            .Filterable()
                            .Sortable()
                            .Scrollable(s => s.Enabled(true).Height("auto"))
                            .Resizable(resize => resize.Columns(true))
                            .DataSource(dataSource => dataSource
                            .Ajax()
                            .PageSize(15)
                            .Events(events => events.Error("error_handler"))
                                .Model(model => model.Id(p => p.QiD))
                                .Read(read => read.Action("Read_AuditTrail", "Attachment", new { Area=""}).Data("Get_ECF_Gid"))
                         ))
                }
            </div>
        </div>
    </div>
    @Html.HiddenFor(m => m.Ref_Gid)
</body>

</html>

<script type="text/javascript">

    function Get_ECF_Gid() {
        debugger;
        var ECF_Gid = $("#HDR_EcfGId").val();
        //var ECF_Gid = $("#ecf_gid").val();
        //var ECF_Gid = 269;
        return { "ECF_Gid": ECF_Gid }
    }
</script>

IEM-Product/IEMProduct/Views/Shared/BatchAttachments.cshtml
@using Kendo.Mvc.UI;
@using Kendo.Mvc.UI.Fluent;
@using Kendo.Mvc.Extensions;
@model  DBHelper.Attachment_Model

<div class="container-fluid" style="margin-left: -2%;margin-top:1%;">
    @Html.HiddenFor(model => model.attach_batch_gid)
    @Html.HiddenFor(model => model.attach_ecf_gid)
    @Html.HiddenFor(model => model.attach_module)
    @Html.HiddenFor(model => model.attach_debitinvoice_flag)
    <div class="col-sm-12">
        @(Html.Kendo().Grid<DBHelper.Attachment_Model>().Name("kgrid_attachments")
            .HtmlAttributes(new { style = "width:100%;line-height:2em;font-weight:normal;height: 50% !important;" })
            .Columns(columns =>
                {
                    columns.Bound(m => m.attachment_gid).Title("Master ID").Hidden();
                    columns.Bound(m => m.ecf_no).Title("Ref No").Width(100);
                    columns.Template(@<text></text>).ClientTemplate("<a style = 'color:blue;cursor:pointer' href='" + Url.Action("Show_documents", "../Attachment") + "/#= attachment_gid #'" + ">#= attachment_filename #</a>").Title("File Name").Width(350);
                    columns.Bound(m => m.docgrpname).Width(80).Title("Doc Group Name").Width(160);
                    columns.Bound(m => m.attachment_desc).Width(83).Title("Description").Width(160);
                    columns.Bound(m => m.attachment_inserted_by).Width(120).Title("Attached By").Width(160);
                    columns.Bound(m => m.attachment_inserted_date).Width(120).Title("Attached Date").Width(160);
                })
                    .Editable(editable => { editable.Mode(GridEditMode.InLine); })
                    .Pageable(pageable => pageable
                    .Refresh(true)
                    .PageSizes(new List<object> { 10, 15, 20, 25 })
                    .ButtonCount(5))
                    .Filterable()
                    .Sortable()
                    .Scrollable(s => s.Enabled(true).Height("auto"))
                    .Resizable(resize => resize.Columns(true))
                    .DataSource(dataSource => dataSource
                    .Ajax()
                    .PageSize(10)
                    .Events(events => events.Error("error_handler"))
                    .Model(model => model.Id(p => p.attachment_gid))
                    .Read(read => read.Action("GetBatchWiseAttachments", "../Attachment").Data("Parameter_values"))
                ))
    </div>
</div>

<script>
    function Parameter_values() {
        debugger;
        var params = {};
        params.attach_batch_gid = $("#attach_batch_gid").val();
        params.attach_ecf_gid = $("#attach_ecf_gid").val();
        params.attach_module = $("#attach_module").val();
        params.attach_debitinvoice_flag = $("#attach_debitinvoice_flag").val();
        return { _ObjModel: params }
    }
</script>

IEM-Product/IEMProduct/Views/Shared/_Layout.cshtml
@using Kendo.Mvc.UI;
@using Kendo.Mvc.UI.Fluent;
@using Kendo.Mvc.Extensions;
@using Kendo.Mvc.Resources;
@{
    DataAccessHandler.Models.IEMProduct.MenuModel menuList = new DataAccessHandler.Models.IEMProduct.MenuModel();
    DBHelper.Profile_Model objUpload = new DBHelper.Profile_Model();
}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv='cache-control' content='no-cache'>
    <meta http-equiv='expires' content='0'>
    <meta http-equiv='pragma' content='no-cache'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>IEM</title>

    @Scripts.Render("~/bundles/js")
    @Styles.Render("~/Content/css")
    <script src="~/Scripts/jquery-confirm.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.min.js"></script>
    @*<link href="~/Content/main.css" rel="stylesheet" />*@
    <style type="text/css">
          div#spinner {
            width: 100%;
            height: 100%;
            top: 0px;
            left: 0px;
            position: fixed;
            display: block;
            opacity: 0.6;
            background: #aaaaaa url('~/Content/Images/ui-bg_flat_0_aaaaaa_40x100.png');
            z-index: 1006;
            text-align: center;
            display: none;
            filter: Alpha(Opacity=30); /*{opacityOverlay}*/
        }
            div#spinner img {
            position: absolute;
            /*width:100px;
               height:100px;*/
            top: 40%;
            left: 42%;
            opacity: 4.5;
            z-index: 1007;
        }
              div#spinner span {
            font-family: Arial Tahoma;
            font-size: large;
            font-weight: bold;
            opacity: 4.5;
            margin-top: 100px;
            color: white;
        }
            
        </style>
</head>
<body>

        <div id="spinner">
            <img src="~/Content/images/Fountain.gif" /> <br /><span>Please Wait...</span>.webp
            @*<img src="~/Content/images/GlowingRing.gif" /> <br /><span>Please Wait...</span>*@
            @*<img src="~/Content/images/Snake.gif" /> <br /><span>Please Wait...</span>*@
            @* <img src="~/Content/images/Fountain.gif" /> <br /><span>Please Wait...</span>*@
            @*<img src="~/Content/images/Segments.gif" /> <br /><span>Please Wait...</span>*@
            @*<img src="~/Content/images/FadingLines.gif" /> <br /><span>Please Wait...</span>*@

        </div>
  
        <div class="container-fluid">
            <div class="row" style="background:#245988;">

                <div class="col-sm-2" style="background: #eee;">
                    <img style="margin: 5px;" src="~/Content/Images/logo-flex.png" />
                </div>

                @(Html.Kendo().Window()
                      .Name("kwindow_employeedetails")
                      .Title("Employee Profile") //set the title of the window
                      .Content(@<text>@Html.Partial("Profile_Partial", objUpload)</text>)
                                                                                                                .Draggable()
                                                                                                                .Resizable()
                                                                                                                .Width(1200)
                                                                                                                .Height(600)
                                                                                                                .Modal(true)
                                                                                                                .Scrollable(false)
                                                                                                                .Visible(false))

                <div class="col-sm-6">
                    <header>
                        <div class="HeaderMenu">
                            <div style="float:left;width:100%;color:white;">
                                @Html.Partial("MenuNew", menuList)

                            </div>
                        </div>
                    </header>
                </div>
                <div class="col-sm-2">
                    <a style="margin:12px;float:right;font-size:17px;color:#fff;">Welcome @Session["Employee_Name"]</a>
                </div>

                <div class="col-sm-1">
                    <table style="margin-left:-34%;">
                        <tr>
                            <td>
                                @*<a href="#" data-toggle="tooltip" title="My Profile" class="fa fa-user" data-target="#Newcust1" onclick="Editcustdetails();">Profile</a>*@
                                <span onclick="return Editcustdetails();" class="fa fa-user" style="color:white;cursor:pointer;"></span>
                                @*@Html.ActionLink(" ", "Profile", "Profile", new { @class="Editcustdetails" }, new { @style = "margin:15px;float:right;font-size:20px;color:#fff;", @class = "fa fa-user" })*@
                            </td>
                            <td>
                                @Html.ActionLink(" ", "WorkBench", "WorkBench", new { Area = "" }, new { @style = "margin:15px;float:right;font-size:20px;color:#fff;", @class = "fa fa-th" })
                            </td>
                            <td>
                                @Html.ActionLink(" ", "Login", "Login", new { Area = "" }, new { @style = "margin:15px;float:right;font-size:20px;color:#fff;", @class = "fa fa-sign-out" })
                            </td>
                        </tr>
                    </table>
                </div>

                <div class="col-sm-1">
                    <img style="margin: 4px;float: left;" src="~/Content/images/iem-logo.png" />
                </div>

            </div>

        </div>


        <div class="container-fluid body-content">
            @RenderBody()

            <footer>
                <div class="row footer mt-5">
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4">
                        <p style="text-align:center;position: relative;top: 5px;">&copy; @DateTime.Now.Year Flexicode Technologies Pvt Ltd.</p>
                    </div>
                    <div class="col-md-4">
                    </div>
                </div>
            </footer>
        </div>

        @RenderSection("scripts", required: false)


</body>

</html>


<script>
    /*Avoid Pasting values in a textbox*/
    $('input').on('paste', function (event) {
        if (event.originalEvent.clipboardData.getData('Text').match(/[^\d]/)) {
            event.preventDefault();
        }
    });
   
    // Show the loader icon
    $(document).ajaxStart(function () {
        // $('#loader').show();
        showProgress();
    });

    // Hide the loader icon
    $(document).ajaxStop(function () {
        // $('#loader').hide();
        hideProgress();
    });
    var spinnerVisible = false;

    function showProgress() {
        if (!spinnerVisible) {
            $("div#spinner").fadeIn("fast");
            spinnerVisible = true;
        }
    }
    function hideProgress() {
        if (spinnerVisible) {
            var spinner = $("div#spinner");
            spinner.stop();
            spinner.fadeOut("fast");
            spinnerVisible = false;
        }
    }


    function Signout() {
        debugger;

        @*var url = '@Url.Action("Login", "../Login")'
        window.location.href = url;*@
    }


    function Editcustdetails()
    {
        debugger;
        var window = $("#kwindow_employeedetails").data("kendoWindow"); //get the Window widget's instance
        window.open();  //and call its open method
        window.center();
        Read_ProfileData();
        TreeView();
    }
    //$('#Editcustdetails').click(function () {
    //    debugger;

    //    var window = $("#kwindow_employeedetails").data("kendoWindow"); //get the Window widget's instance
    //    window.open();  //and call its open method
    //    window.center();
    //});
    //function Editcustdetails() {
    //    debugger;
    //    //$("#Profile").data("kendoWindow").open();

    //    var window = $("#kwindow_profile").data("kendoWindow"); //get the Window widget's instance
    //    window.open();  //and call its open method
    //    window.center();
    //}
    @*function Editcustdetails() {
        debugger;
        $.ajax({
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: {},
            dataType: "html",
            url: '@Url.Action("Profile", "Profile")',
            success: function (data) {
                debugger;
                $("#Newcust1").html(data);
            },
            error: function (data) {
                $.alert({
                    title: 'DMS',
                    content: 'Error' + data,
                    type: 'red',
                });
            }
        });
    }*@

</script>